version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - chmod +x aws_scripts/build.sh
      - echo IM Client Build started on `date`
      - aws_scripts/build.sh mvn -B package
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/cleanup
    - front-end-vue/dist/**/*
