version: 0.2
run-as: root

phases:
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
  build:
    commands:
      - chmod +x aws_scripts/build.sh
      - cd $CODEBUILD_SRC_DIR/front-end-vue
      - npm install
      - npm run test:unit
      - $CODEBUILD_SRC_DIR/aws_scripts/build.sh npm run build
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/cleanup
    - front-end-vue/dist/**/*
