version: 0.2

phases:
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get -y update
      - apt-get -y install google-chrome-stable
  build:
    commands:
      # Build Front End
      - $CODEBUILD_SRC_DIR
      - chmod +x aws_scripts/build.sh
      - echo IM Client Build started on `date`
      - aws_scripts/build.sh mvn -B package
      - mvn sonar:sonar
      # Build back end
      - cd $CODEBUILD_SRC_DIR_API
      - chmod +x aws_scripts/build.sh
      - echo IM API Build started on `date`
      - aws_scripts/build.sh mvn -B package
      - mvn sonar:sonar
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/**/*
    - FrontEndv8/dist/FrontEndv8/**/*
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR_API
      files:
        - target/IMAPI.war
